parameters:
    whatwedo_crud.menu_builder.class: 'whatwedo\CrudBundle\Menu\MenuBuilder'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    whatwedo\CrudBundle\:
        resource: '../../*'
        exclude:
            - '../../Normalizer/'


    whatwedo\CrudBundle\View\DefinitionBuilder:
        shared: false

    whatwedo\CrudBundle\View\DefinitionView:
        shared: false

    whatwedo\CrudBundle\Block\:
        resource: '*'
        shared: false

    whatwedo\CrudBundle\Content\:
        resource: '*'
        shared: false

    whatwedo\CrudBundle\Routing\CrudLoader:
        tags:
            - { name: routing.loader }

    whatwedo\CrudBundle\EventListener\CrudDefinitionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    whatwedo\CrudBundle\Extension\BreadcrumbsExtension:
        arguments:
            - '@white_october_breadcrumbs'
            - '%whatwedo_crud.config.breadcrumbs.home.text%'
            - '%whatwedo_crud.config.breadcrumbs.home.route%'

    whatwedo\CrudBundle\Manager\BlockManager:
        arguments:
            - !tagged_iterator 'whatwedo_crud.block'

    whatwedo\CrudBundle\Manager\ContentManager:
        arguments:
            - !tagged_iterator 'whatwedo_crud.content'

    whatwedo\CrudBundle\Manager\DefinitionManager:
        arguments:
            - !tagged_iterator 'whatwedo_crud.definition'


    whatwedo\CrudBundle\Maker\MakeDefinition:
        arguments:
            - '@maker.doctrine_helper'
            - '@maker.renderer.form_type_renderer'
            - '%kernel.project_dir%'
            - '@whatwedo\CoreBundle\Manager\FormatterManager'
        tags:
            - { name: maker.command }

    whatwedo_crud.menu_builder:
        class: '%whatwedo_crud.menu_builder.class%'
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSubMenu, alias: sub }
